#include "dmc_rengine/profiles/dmc3/recovered_source_tree.hpp"

#include <algorithm>

namespace dmc::rengine::profiles::dmc3 {
namespace {

using Kind = RecoveredSourceKind;
using Status = RecoveredSourceStatus;

[[nodiscard]] const std::vector<RecoveredSourceSymbol>& tree_storage() {
    static const std::vector<RecoveredSourceSymbol> tree{
        {.id="dmc3.resource-runtime", .parent_id="", .kind=Kind::subsystem, .name="Resource Runtime", .summary="Recovered DMC3 resource selection, byte acquisition, materialization and lifecycle runtime.", .status=Status::very_high, .evidence_passes={3,6,18,19,21,25,27,28,29,45,46,49,50,51,53}},
        {.id="dmc3.resource-runtime.vfs", .parent_id="dmc3.resource-runtime", .kind=Kind::subsystem, .name="VFS / Mounts", .summary="Executable-relative bootstrap, provider normalization, mount precedence and logical candidate selection.", .status=Status::very_high, .evidence_passes={3,20,21,22,45,46,49,51}},
        {.id="dmc3.resource-runtime.io", .parent_id="dmc3.resource-runtime", .kind=Kind::subsystem, .name="FileSlot / Async I/O", .summary="Physical/archive backend handles, 100-slot file pool, requests, callback ABI and whole-file materialization spine.", .status=Status::very_high, .evidence_passes={6,19,27,29,49,50,53}},
        {.id="dmc3.resource-runtime.zip", .parent_id="dmc3.resource-runtime", .kind=Kind::subsystem, .name="ZIP / NBZ Backend", .summary="Classic ZIP index, member streams, raw-DEFLATE inflater, seek/reset and integrity behavior.", .status=Status::very_high, .evidence_passes={3,11,13,15,18,21,22}},
        {.id="dmc3.resource-runtime.loaded", .parent_id="dmc3.resource-runtime", .kind=Kind::subsystem, .name="LoadedResource Registry", .summary="363-record resource registry, allocation, state transitions, typed post-load, release and reset policies.", .status=Status::very_high, .evidence_passes={19,24,25,27,28,29,30,31,32}},
        {.id="dmc3.resource-runtime.lst", .parent_id="dmc3.resource-runtime", .kind=Kind::subsystem, .name="Loose Container / .lst", .summary="Packed-first representation selection and recursive loose PAC/PNST-compatible synthesis.", .status=Status::very_high, .evidence_passes={25,26,46,47,49,53,54}},
        {.id="dmc3.gameplay-loader", .parent_id="", .kind=Kind::subsystem, .name="Gameplay Composite Loader", .summary="Higher-level component nodes, claims, stage/demo/enemy composite requests and replacement barriers.", .status=Status::very_high, .evidence_passes={28,30,31,32}},
        {.id="dmc3.scene-lifecycle", .parent_id="", .kind=Kind::subsystem, .name="Scene Lifecycle", .summary="Scene manager transitions, selective/full resource reset, gameplay re-entry and continue/death flows.", .status=Status::very_high, .evidence_passes={30,31,32}},
        {.id="dmc3.stage-resource-topology", .parent_id="", .kind=Kind::subsystem, .name="Stage Resource Topology", .summary="Executable-backed stage main/CFG/effect identities and st001 composite ordering.", .status=Status::very_high, .evidence_passes={31,32}},
        {.id="dmc3.texture-runtime", .parent_id="", .kind=Kind::subsystem, .name="Texture Runtime", .summary="Texture parse/cache/runtime registration and gfxTexture ownership path.", .status=Status::high, .evidence_passes={24}},

        {.id="dmc3.vfs.Dmc3ResourceBootstrap", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::function, .name="Dmc3ResourceBootstrap", .summary="Derives executable-relative data\\dmc3 root and probes contiguous DMC3-%d.nbz volumes from index zero until first miss.", .status=Status::very_high, .va=0x14002E930ULL, .evidence_passes={3,32,45}, .attributes={{"numbered_domain","0..INT32_MAX"},{"archive_effective_precedence","N..0"}}},
        {.id="dmc3.vfs.OpenGameResource", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::function, .name="OpenGameResource", .summary="Strips to basename, tries six namespace prefixes, completes archive-provider pass before physical-provider pass.", .status=Status::very_high, .va=0x14002FCA0ULL, .evidence_passes={3,20,32,49}, .attributes={{"candidate_count","12"},{"candidate_buffer","0x400"}}},
        {.id="dmc3.vfs.ResourcePathNormalize", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::function, .name="ResourcePathNormalize", .summary="Canonicalizes separators, trims boundaries and applies optional ASCII case conversion.", .status=Status::very_high, .va=0x140327160ULL, .evidence_passes={3,13,45,51}, .attributes={{"archive_flags","0x0E"},{"physical_flags","0x0C"}}},
        {.id="dmc3.vfs.ResourceMountResolve", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::function, .name="ResourceMountResolve", .summary="Traverses global mount list; archive mounts use normalized ZIP lookup, physical mounts normalize then join to mounted root/open backend.", .status=Status::very_high, .va=0x140327430ULL, .evidence_passes={3,45,46,49}},
        {.id="dmc3.vfs.ResourcePathExists", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::function, .name="ResourcePathExists", .summary="Provider-level existence check; ordinary missing/path-not-found becomes false in recovered bootstrap behavior.", .status=Status::high, .va=0x140327720ULL, .evidence_passes={46,49,53}},
        {.id="dmc3.vfs.PhysicalMountAdd", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::function, .name="PhysicalMountAdd", .summary="Allocates and prepends a type-0 physical root mount node using DMC3 normalization flags 0x0C.", .status=Status::very_high, .va=0x140326D20ULL, .evidence_passes={20,29,45,46}},
        {.id="dmc3.vfs.ArchiveMountAdd", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::function, .name="ArchiveMountAdd", .summary="Allocates and prepends a type-1 ZIP/NBZ mount and builds its embedded archive index.", .status=Status::very_high, .va=0x140326DA0ULL, .evidence_passes={20,29,45}},
        {.id="dmc3.vfs.mount-list", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::global, .name="g_resource_mount_head", .summary="Global prepended resource-mount linked-list head.", .status=Status::very_high, .va=0x140CF3180ULL, .evidence_passes={3,20,29,45}},
        {.id="dmc3.vfs.namespace-prefixes", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::table, .name="g_resource_namespace_prefixes", .summary="Six logical prefixes: GDataX360.afs/, GData.afs/, Video/, afs/sound/, SAVEDATA/, empty.", .status=Status::confirmed, .va=0x14055AEF8ULL, .evidence_passes={20}},
        {.id="dmc3.vfs.physical-final-open", .parent_id="dmc3.resource-runtime.vfs", .kind=Kind::policy, .name="Physical final-open semantics", .summary="Final Win32 filename case/alias/error mapping after 0x0C normalization remains unresolved.", .status=Status::open, .evidence_passes={45,46,49,51,52}},

        {.id="dmc3.io.FileSlot", .parent_id="dmc3.resource-runtime.io", .kind=Kind::struct_type, .name="FileSlot", .summary="Global fixed-size open-file slot used by physical and archive-backed handles.", .status=Status::high, .size=0x20ULL, .evidence_passes={6,29}, .attributes={{"pool_count","100"}}},
        {.id="dmc3.io.file-slot-pool", .parent_id="dmc3.resource-runtime.io", .kind=Kind::registry, .name="g_file_slots", .summary="100 FileSlot entries protected by a global critical section.", .status=Status::very_high, .va=0x140C18E60ULL, .size=0xC80ULL, .evidence_passes={6,29}},
        {.id="dmc3.io.file-slot-critical-section", .parent_id="dmc3.resource-runtime.io", .kind=Kind::global, .name="g_file_slot_cs", .summary="Critical section protecting FileSlot allocation/release; no recovered normal destruction path.", .status=Status::very_high, .va=0x140C19AE0ULL, .evidence_passes={6,29}},
        {.id="dmc3.io.AsyncIOThread", .parent_id="dmc3.resource-runtime.io", .kind=Kind::struct_type, .name="AsyncIOThread", .summary="Lazy async request service with deque<Request*> and request-ticket serial.", .status=Status::high, .size=0x58ULL, .evidence_passes={6,29}},
        {.id="dmc3.io.async-io-global", .parent_id="dmc3.resource-runtime.io", .kind=Kind::global, .name="g_async_io", .summary="Lazy heap pointer to AsyncIOThread service.", .status=Status::high, .va=0x1405D9C50ULL, .evidence_passes={6,29}},
        {.id="dmc3.io.AsyncIOThread.Init", .parent_id="dmc3.resource-runtime.io", .kind=Kind::method, .name="AsyncIOThread::Init", .summary="Initializes async I/O service state.", .status=Status::high, .va=0x14002E530ULL, .evidence_passes={6,29}},
        {.id="dmc3.io.AsyncIOThread.Shutdown", .parent_id="dmc3.resource-runtime.io", .kind=Kind::method, .name="AsyncIOThread::Shutdown", .summary="Destroys worker/request/deque state; directly recovered on startup-failure cleanup, not normal process exit.", .status=Status::high, .va=0x14002E680ULL, .evidence_passes={6,29}},
        {.id="dmc3.io.SubmitReadRequest", .parent_id="dmc3.resource-runtime.io", .kind=Kind::function, .name="SubmitReadRequest", .summary="Submits ReadRequestV2 to synchronous/asynchronous file acquisition spine.", .status=Status::high, .va=0x14002EA40ULL, .evidence_passes={19,49}},
        {.id="dmc3.io.AsyncIOWorker", .parent_id="dmc3.resource-runtime.io", .kind=Kind::function, .name="AsyncIOWorker", .summary="Pops polymorphic Request objects and invokes Request::Execute().", .status=Status::high, .va=0x14002FAE0ULL, .evidence_passes={6}},
        {.id="dmc3.io.AsyncIOThreadEntry", .parent_id="dmc3.resource-runtime.io", .kind=Kind::function, .name="AsyncIOThreadEntry", .summary="_beginthreadex worker entry thunk; recovered stack size 0x10000.", .status=Status::high, .va=0x14002FC70ULL, .evidence_passes={6}},
        {.id="dmc3.io.FileSlotClose", .parent_id="dmc3.resource-runtime.io", .kind=Kind::function, .name="FileSlotClose", .summary="Closes FileBackendHandle/raw physical handle, then returns slot to pool.", .status=Status::very_high, .va=0x140048CB0ULL, .evidence_passes={29}},
        {.id="dmc3.io.FileBackendHandleDestroy", .parent_id="dmc3.resource-runtime.io", .kind=Kind::function, .name="FileBackendHandleDestroy", .summary="Destroys ZIP entry stream or physical backend handle wrapper.", .status=Status::very_high, .va=0x140326EA0ULL, .evidence_passes={29}},
        {.id="dmc3.io.ReadRequestV2", .parent_id="dmc3.resource-runtime.io", .kind=Kind::struct_type, .name="ReadRequestV2", .summary="Read request carrying callback, offset, destination, byte count, context, FileSlot ID and ticket.", .status=Status::very_high, .size=0x38ULL, .evidence_passes={6,19,49}, .attributes={{"callback","+0x08"},{"file_offset","+0x10"},{"destination","+0x18"},{"requested_bytes","+0x20"},{"user_context","+0x28"},{"file_slot_id","+0x30"},{"ticket_id","+0x34"}}},
        {.id="dmc3.io.AsyncWholeFileLoad", .parent_id="dmc3.resource-runtime.io", .kind=Kind::struct_type, .name="AsyncWholeFileLoadV1", .summary="0x50-byte whole-file load state; owns progress/open state but not destination bytes.", .status=Status::high, .size=0x50ULL, .evidence_passes={19,49}},
        {.id="dmc3.io.OpenWholeFileLoad", .parent_id="dmc3.resource-runtime.io", .kind=Kind::function, .name="OpenWholeFileLoad", .summary="Calls OpenGameResource, gets signed FileSlot ID, queries size and allocates whole-file load state.", .status=Status::very_high, .va=0x1400333F0ULL, .evidence_passes={19,49}},
        {.id="dmc3.io.ComputeWholeFileChunkCount", .parent_id="dmc3.resource-runtime.io", .kind=Kind::function, .name="ComputeWholeFileChunkCount", .summary="Computes ceil(totalBytes/0x800) transfer chunks.", .status=Status::very_high, .va=0x1400333C0ULL, .evidence_passes={19,49}},
        {.id="dmc3.io.SubmitWholeFileChunks", .parent_id="dmc3.resource-runtime.io", .kind=Kind::function, .name="SubmitWholeFileChunks", .summary="Submits chunkCount<<11 bytes into caller-owned destination.", .status=Status::very_high, .va=0x140033500ULL, .evidence_passes={19,49}},
        {.id="dmc3.io.WholeFileCompletion", .parent_id="dmc3.resource-runtime.io", .kind=Kind::function, .name="WholeFileCompletion", .summary="callback(ticketId,userContext,errorFlag,bytesRead); advances loadedBytes or records error.", .status=Status::very_high, .va=0x1400335A0ULL, .evidence_passes={19,49}},

        {.id="dmc3.zip.ZipCentralEntryV1", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::struct_type, .name="ZipCentralEntryV1", .summary="Parsed classic ZIP central-directory record object.", .status=Status::very_high, .size=0x50ULL, .evidence_passes={15,18,21}},
        {.id="dmc3.zip.ZipArchiveIndexV1", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::struct_type, .name="ZipArchiveIndexV1", .summary="Archive-owned central list plus sorted normalized lookup array.", .status=Status::very_high, .size=0x40ULL, .evidence_passes={15,22,45}, .attributes={{"central_head","+0x28"},{"lookup_array","+0x30"},{"entry_count","+0x38"},{"lookup_element_size","0x10"}}},
        {.id="dmc3.zip.ZipRawSubstreamV1", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::struct_type, .name="ZipRawSubstreamV1", .summary="Bounded compressed/stored member substream with physical file, data offset, position and logical storage size.", .status=Status::very_high, .size=0x18ULL, .evidence_passes={11,15,18}},
        {.id="dmc3.zip.ZipEntryStreamV1", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::struct_type, .name="ZipEntryStreamV1", .summary="Lazy member stream containing archive path, copied central header, raw substream, optional inflater and logical position.", .status=Status::very_high, .size=0x50ULL, .evidence_passes={11,15,18}},
        {.id="dmc3.zip.ZipInflaterV1", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::struct_type, .name="ZipInflaterV1", .summary="Raw-DEFLATE stream state with 0x1000 input buffer and embedded z_stream.", .status=Status::very_high, .size=0x1080ULL, .evidence_passes={15,18}, .attributes={{"raw_substream","+0x0000"},{"logical_size","+0x0008"},{"logical_position","+0x000C"},{"input_buffer","+0x0010..+0x100F"},{"z_stream","+0x1010"},{"terminal_latch","+0x1068"},{"refill_cursor_end","+0x1070/+0x1078"}}},
        {.id="dmc3.zip.ZipArchiveBuildIndex", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipArchiveBuildIndex", .summary="Normalizes names with 0x0E, fills {normalizedName,entry*} array, qsorts it and retains all comparator-equal entries.", .status=Status::very_high, .va=0x140327CC0ULL, .evidence_passes={3,15,22,45}},
        {.id="dmc3.zip.ZipArchiveLookup", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipArchiveLookup", .summary="Normalizes request with 0x0E then CRT bsearches sorted lookup array.", .status=Status::very_high, .va=0x140328160ULL, .evidence_passes={3,13,22}},
        {.id="dmc3.zip.ZipEntryNameCompare", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipEntryNameCompare", .summary="Bytewise NUL-terminated comparator with no duplicate-key secondary tie-break.", .status=Status::very_high, .va=0x1403291D0ULL, .evidence_passes={3,22}},
        {.id="dmc3.zip.ZipInflaterInit", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipInflaterInit", .summary="Rewinds raw substream, zeroes z_stream and initializes zlib 1.2.5 with windowBits=-15.", .status=Status::very_high, .va=0x140327BE0ULL, .evidence_passes={18}},
        {.id="dmc3.zip.ZipMemberConstruct", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipMemberConstruct", .summary="Reads local header, derives dataOffset from local header/name/extra lengths and creates raw or inflated member state from central metadata.", .status=Status::very_high, .va=0x140328360ULL, .evidence_passes={18,21,54}},
        {.id="dmc3.zip.ZipEntryPrepare", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipEntryPrepare", .summary="Lazy-realizes archive file/member stream and synchronizes to requested logical position.", .status=Status::very_high, .va=0x140328540ULL, .evidence_passes={18}},
        {.id="dmc3.zip.InflateProgress", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="InflateProgress", .summary="One bounded inflate-progress operation used by compressed seek/reset replay.", .status=Status::very_high, .va=0x140328680ULL, .evidence_passes={18}},
        {.id="dmc3.zip.InflateRead", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="InflateRead", .summary="Refills up to 0x1000 compressed bytes, calls inflate core, handles stream-end/Z_BUF_ERROR and returns produced bytes or -1.", .status=Status::very_high, .va=0x140328820ULL, .evidence_passes={3,15,18}},
        {.id="dmc3.zip.ZipCentralWalk", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipCentralWalk", .summary="Reads central records until EOCD signature at a record boundary; does not use EOCD entriesTotal as walker bound.", .status=Status::very_high, .va=0x1403289F0ULL, .evidence_passes={21}},
        {.id="dmc3.zip.FindEOCD", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="FindEOCD", .summary="Backward-scans for EOCD and accepts only when EOCD+declared comment ends exactly at EOF.", .status=Status::very_high, .va=0x140328C30ULL, .evidence_passes={21}},
        {.id="dmc3.zip.ParseEOCD", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ParseEOCD", .summary="Parses classic EOCD; central start in recovered backend is absoluteEOCDOffset-centralDirectorySize.", .status=Status::very_high, .va=0x140328D80ULL, .evidence_passes={21}},
        {.id="dmc3.zip.ZipEntryRead", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipEntryRead", .summary="Dispatches compressed entries to InflateRead; stored entries clamp/direct-read raw bounded substream.", .status=Status::very_high, .va=0x140328F50ULL, .evidence_passes={3,15,18}},
        {.id="dmc3.zip.ZipCompressedSeek", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipCompressedSeek", .summary="SET/CUR/END seek implemented as zlib teardown, full reset and inflate/discard replay from member start.", .status=Status::very_high, .va=0x140328FE0ULL, .evidence_passes={18}},
        {.id="dmc3.zip.ZipStoredSeek", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipStoredSeek", .summary="SET/CUR/END logical seek mapped to dataOffset+position for stored/raw stream.", .status=Status::very_high, .va=0x1403290F0ULL, .evidence_passes={18}},
        {.id="dmc3.zip.ZipEntryStreamDestroy", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipEntryStreamDestroy", .summary="Destroys zlib state, closes underlying file, frees raw/inflater/path state.", .status=Status::very_high, .va=0x140327DB0ULL, .evidence_passes={18,29}},
        {.id="dmc3.zip.ZipEntryObjectDestroy", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::function, .name="ZipEntryObjectDestroy", .summary="Final ZipEntryStream object free after stream teardown.", .status=Status::very_high, .va=0x140327D90ULL, .evidence_passes={18,29}},
        {.id="dmc3.zip.original-integrity-policy", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::policy, .name="Original ZIP acceptance policy", .summary="CRC/flags are decoded but no recovered CRC compare or broad flag rejection exists in bounded original backend; product hardening is a separate axis.", .status=Status::high, .evidence_passes={21}},
        {.id="dmc3.zip.duplicate-key-policy", .parent_id="dmc3.resource-runtime.zip", .kind=Kind::policy, .name="Normalized duplicate-key behavior", .summary="Comparator-equal names remain CRT qsort/bsearch ambiguity; no semantic original winner rule is evidenced.", .status=Status::very_high, .evidence_passes={22}},

        {.id="dmc3.loaded.LoadedResourceRecord", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::struct_type, .name="LoadedResourceRecord", .summary="Generic resource registry record with group, state, callback, TypeInfo, payload and backing subobject.", .status=Status::very_high, .size=0x48ULL, .evidence_passes={25,27,28}, .attributes={{"group","+0x00"},{"state","+0x04"},{"selector_family_metadata","+0x08"},{"ready_callback","+0x10"},{"type_info","+0x18"},{"payload","+0x20"},{"backing","+0x28..+0x47"}}},
        {.id="dmc3.loaded.ResourceTypeInfo", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::struct_type, .name="ResourceTypeInfo", .summary="Resource descriptor with kind16 at +0 and full logical resource path pointer at +8.", .status=Status::very_high, .evidence_passes={19,25,28}, .attributes={{"kind16","+0x00"},{"path","+0x08"},{"descriptor_stride","0x10"}}},
        {.id="dmc3.loaded.registry", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::registry, .name="g_loaded_resources", .summary="Exactly 363 LoadedResourceRecord entries of stride 0x48.", .status=Status::very_high, .va=0x140C99D30ULL, .size=0x6618ULL, .evidence_passes={25,27,28,29}},
        {.id="dmc3.loaded.group-counts", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::table, .name="g_loaded_resource_group_counts", .summary="Seven canonical group capacities [4,136,60,28,1,128,6].", .status=Status::confirmed, .va=0x140581A10ULL, .evidence_passes={28}},
        {.id="dmc3.loaded.group-bases", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::table, .name="g_loaded_resource_group_bases", .summary="Cumulative group bases [0,4,140,200,228,229,357,363].", .status=Status::confirmed, .va=0x140581A20ULL, .evidence_passes={28}},
        {.id="dmc3.loaded.state-machine", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::state_machine, .name="LoadedResource state machine", .summary="Forward path 0 free -> 1 materializing -> 2 bytes complete/post-load pending -> 3 ready. Cancellation path 1|2 -> 4 pending cleanup -> 0.", .status=Status::very_high, .evidence_passes={25,27,30}},
        {.id="dmc3.loaded.ManagerConstruct", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="LoadedResourceManagerConstruct", .summary="Constructs 363 registry records.", .status=Status::very_high, .va=0x1401B78F0ULL, .evidence_passes={27,29}},
        {.id="dmc3.loaded.SelectRepresentation", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="SelectContainerRepresentation", .summary="For kind16==0: mode1 exact packed target, else mode2 matching .lst fallback, else mode0 failure.", .status=Status::very_high, .va=0x1401B79E0ULL, .evidence_passes={25,26,47,53}},
        {.id="dmc3.loaded.ComputeRequiredBacking", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="ComputeRequiredBacking", .summary="Computes direct rounded size or packed/.lst container backing requirement.", .status=Status::very_high, .va=0x1401B7B90ULL, .evidence_passes={25,53}},
        {.id="dmc3.loaded.InitializeRegistry", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="InitializeLoadedResourceRegistry", .summary="Resets all 363 records and writes canonical group IDs from group partition tables.", .status=Status::very_high, .va=0x1401B8380ULL, .evidence_passes={28}},
        {.id="dmc3.loaded.CancelUnfinished", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="CancelUnfinishedResources", .summary="Marks states 1/2 as state4 after scheduler rollback and queues deferred cleanup.", .status=Status::very_high, .va=0x1401B8430ULL, .evidence_passes={27,30}},
        {.id="dmc3.loaded.IsQuiescent", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="LoadedResourceRegistryIsQuiescent", .summary="True only when all records are state0 or state3.", .status=Status::very_high, .va=0x1401B84B0ULL, .evidence_passes={27,30}},
        {.id="dmc3.loaded.AcquireRecord", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="AcquireLoadedResource", .summary="Stores TypeInfo, allocates backing/payload, starts materialization and writes state1 only after successful scheduling.", .status=Status::very_high, .va=0x1401B84E0ULL, .evidence_passes={25,32,49,50}},
        {.id="dmc3.loaded.MaterializeDispatch", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="MaterializeResourceDispatch", .summary="Dispatches direct/packed resources to shared submission wrapper or mode2 to loose-container synthesizer.", .status=Status::very_high, .va=0x1401B8CA0ULL, .evidence_passes={25,48,49,50}},
        {.id="dmc3.loaded.MaterializationComplete", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="LoadedResourceMaterializationComplete", .summary="Completion callback resolves registry record from context and promotes state1 to state2.", .status=Status::very_high, .va=0x1401B8DC0ULL, .evidence_passes={25,32}},
        {.id="dmc3.loaded.DynamicPoolAcquire", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="DynamicLoadedResourceAcquire", .summary="Group5 first-free allocator over 128 records; returns retained record handle.", .status=Status::very_high, .va=0x1401B8DF0ULL, .evidence_passes={28,30,31,32}},
        {.id="dmc3.loaded.DeferredState4Cleanup", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="DeferredState4Cleanup", .summary="State4 records are set to state0 then backing is released; release return is ignored in this deferred path.", .status=Status::very_high, .va=0x1401B8F00ULL, .evidence_passes={27}},
        {.id="dmc3.loaded.FinalizeReady", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="FinalizeLoadedResources", .summary="For state2: traverses PAC members or direct payload through recursive typed dispatcher, runs optional callback and sets state3.", .status=Status::very_high, .va=0x1401B92D0ULL, .evidence_passes={25,32}},
        {.id="dmc3.loaded.ReleaseRecord", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="ReleaseLoadedResource", .summary="Ordinary owner release; backing-release success transitions record to state0, failure preserves state.", .status=Status::very_high, .va=0x1401B9530ULL, .evidence_passes={27,28,29,30,32}},
        {.id="dmc3.loaded.ResetGroup", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="ResetLoadedResourceGroup", .summary="Resets a contiguous canonical registry group and forces state0.", .status=Status::very_high, .va=0x1401B9560ULL, .evidence_passes={27,30}},
        {.id="dmc3.loaded.ResetAll", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="ResetAllLoadedResources", .summary="Releases all 363 backings and forces every record state0.", .status=Status::very_high, .va=0x1401B95E0ULL, .evidence_passes={27,29,30}},
        {.id="dmc3.loaded.RecursiveTypedDispatch", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::function, .name="RecursiveTypedPostLoadDispatch", .summary="Routes MOD/EFM/SCM/SHW and recursively traverses PNST declared slots; other identities ignored by this dispatcher.", .status=Status::very_high, .va=0x1401B9FA0ULL, .evidence_passes={25}},
        {.id="dmc3.loaded.registry-policy", .parent_id="dmc3.resource-runtime.loaded", .kind=Kind::policy, .name="Registry identity policy", .summary="Original registry is not one normalized-path cache: fixed topology groups coexist with dynamic group5; no universal LoadedResource refcount or generic in-flight coalescing is evidenced.", .status=Status::very_high, .evidence_passes={28}},

        {.id="dmc3.lst.ParseMagic", .parent_id="dmc3.resource-runtime.lst", .kind=Kind::function, .name="ParseLooseContainerMagic", .summary="Leading / is comment/skip; # copies up to four immediate bytes as magic; ordinary content defaults magic to PAC\\0.", .status=Status::very_high, .va=0x1401B7C70ULL, .evidence_passes={26,46}},
        {.id="dmc3.lst.EnumerateChildren", .parent_id="dmc3.resource-runtime.lst", .kind=Kind::function, .name="EnumerateLooseContainerChildren", .summary="Skips /,#,blank control lines; normal CR-terminated tokens preserve declared slot order and join to base directory.", .status=Status::very_high, .va=0x1401B7D10ULL, .evidence_passes={26,46}},
        {.id="dmc3.lst.ResolveNthChild", .parent_id="dmc3.resource-runtime.lst", .kind=Kind::function, .name="ResolveNthLooseChild", .summary="Returns full child path and list-byte location using same grammar/order as child enumerator.", .status=Status::very_high, .va=0x1401B7E60ULL, .evidence_passes={26}},
        {.id="dmc3.lst.ComputeSynthesizedSize", .parent_id="dmc3.resource-runtime.lst", .kind=Kind::function, .name="ComputeSynthesizedContainerSize", .summary="Starts at align64((slotCount+2)*4), adds align64(childMaterializedSize), preserving dummy sparse slots.", .status=Status::very_high, .va=0x1401B7FD0ULL, .evidence_passes={26,53}},
        {.id="dmc3.lst.SynthesizeContainer", .parent_id="dmc3.resource-runtime.lst", .kind=Kind::function, .name="SynthesizeLooseContainer", .summary="Writes magic/slotCount/relativeOffsets, 64-byte aligns children, supports exact lowercase dummy and recursive nested .lst with sibling .pac precedence.", .status=Status::very_high, .va=0x1401B85C0ULL, .evidence_passes={25,26,46,54}},
        {.id="dmc3.lst.MaterializationSubmit", .parent_id="dmc3.resource-runtime.lst", .kind=Kind::function, .name="ResourceMaterializationSubmit", .summary="Shared full-path submission/scheduling wrapper used by direct, packed and loose child loads; internal provider policy and fourth parameter numeric meaning remain unresolved.", .status=Status::partial, .va=0x1402EF4D0ULL, .evidence_passes={48,49,50,53}},
        {.id="dmc3.lst.policy", .parent_id="dmc3.resource-runtime.lst", .kind=Kind::policy, .name="Loose-container representation policy", .summary="Existing positive-size packed resource wins; .lst is fallback. Nested .lst first checks sibling .pac. List scan ceiling 0x1FC0, child token bound 0x100; CRLF behavior is canonical.", .status=Status::very_high, .evidence_passes={26,46}},

        {.id="dmc3.loader.LoaderNode", .parent_id="dmc3.gameplay-loader", .kind=Kind::struct_type, .name="GameplayLoaderNode", .summary="Higher-level logical component node owning a LoadedResource handle and shared-consumer claim count.", .status=Status::very_high, .evidence_passes={30,31}, .attributes={{"loaded_resource","+0x18"},{"active_flag","+0x20"},{"kind","+0x24"},{"logical_id","+0x28"},{"claim_count","+0x2C"}}},
        {.id="dmc3.loader.CreateNode", .parent_id="dmc3.gameplay-loader", .kind=Kind::function, .name="CreateOrReuseLoaderNode", .summary="Matches/reuses node by (kind,id), otherwise selects TypeInfo family and allocates underlying group5 LoadedResource.", .status=Status::very_high, .va=0x1401AE310ULL, .evidence_passes={31,32}},
        {.id="dmc3.loader.ClaimNode", .parent_id="dmc3.gameplay-loader", .kind=Kind::function, .name="ClaimReadyLoaderNode", .summary="Scans ready nodes for (kind,id), increments node claim count and returns node.", .status=Status::very_high, .va=0x1401AE220ULL, .evidence_passes={30,32}},
        {.id="dmc3.loader.ReleaseClaim", .parent_id="dmc3.gameplay-loader", .kind=Kind::function, .name="ReleaseLoaderNodeClaim", .summary="Finds matching ready/pending node and decrements claim count.", .status=Status::very_high, .va=0x1401AF6A0ULL, .evidence_passes={30,32}},
        {.id="dmc3.loader.SweepZeroClaim", .parent_id="dmc3.gameplay-loader", .kind=Kind::function, .name="SweepZeroClaimLoaderNodes", .summary="Eligible zero-claim inactive nodes release underlying LoadedResource through ordinary record release.", .status=Status::very_high, .va=0x1401AF6F0ULL, .evidence_passes={30,32}},
        {.id="dmc3.loader.RequestPrimary", .parent_id="dmc3.gameplay-loader", .kind=Kind::function, .name="RequestPrimaryGameplayComposite", .summary="Primary composite request mode; active replacement first enters cancellation/quiescence barrier.", .status=Status::very_high, .va=0x1401AEDE0ULL, .evidence_passes={30,31,32}},
        {.id="dmc3.loader.RequestAlternate", .parent_id="dmc3.gameplay-loader", .kind=Kind::function, .name="RequestAlternateComposite", .summary="Alternate/demo dynamic composite request mode sharing same cancellation barrier.", .status=Status::very_high, .va=0x1401AE5B0ULL, .evidence_passes={30,31}},
        {.id="dmc3.loader.UpdateCoordinator", .parent_id="dmc3.gameplay-loader", .kind=Kind::function, .name="GameplayLoaderUpdateCoordinator", .summary="Promotes state3-backed nodes to ready; in replacement state waits registry quiescence, detaches stale pending nodes, then launches deferred request.", .status=Status::very_high, .va=0x1401AEEA0ULL, .evidence_passes={30,32}},
        {.id="dmc3.loader.PrimaryCompositeStateMachine", .parent_id="dmc3.gameplay-loader", .kind=Kind::state_machine, .name="PrimaryCompositeStateMachine", .summary="StageCfg lead: create kind1, wait ready and consume CFG physical slot9, then create StageMain kind0 and StageEffect kind2, then wait pending drain.", .status=Status::very_high, .va=0x1401AF000ULL, .evidence_passes={31,32}},
        {.id="dmc3.loader.PlayerResourcePreload", .parent_id="dmc3.gameplay-loader", .kind=Kind::function, .name="PlayerResourcePreloadCoordinator", .summary="Coordinates player body, motion, weapon and transformation-form fixed registry groups from configuration state.", .status=Status::very_high, .va=0x1401DF320ULL, .evidence_passes={31,32}},
        {.id="dmc3.loader.kind-map", .parent_id="dmc3.gameplay-loader", .kind=Kind::policy, .name="CompositeResourceKind map", .summary="Kinds: 0 StageMain, 1 StageCfg, 2 StageEffect, 3 DemoPackage, 4 DemoMessage, 5 EnemyObject, 6 EnemySound.", .status=Status::very_high, .evidence_passes={31}},
        {.id="dmc3.loader.replacement-barrier", .parent_id="dmc3.gameplay-loader", .kind=Kind::policy, .name="Replacement barrier", .summary="cancel/mark unfinished -> wait registry quiescence -> detach stale pending nodes -> start deferred replacement.", .status=Status::very_high, .evidence_passes={30}},

        {.id="dmc3.scene.CSceneGame", .parent_id="dmc3.scene-lifecycle", .kind=Kind::class_type, .name="CSceneGame", .summary="Outer gameplay scene owning common package setup, gameplay scene manager and selective/full resource reset.", .status=Status::very_high, .evidence_passes={30,31}},
        {.id="dmc3.scene.CSceneGame.Teardown", .parent_id="dmc3.scene.CSceneGame", .kind=Kind::method, .name="CSceneGame::Teardown", .summary="Selects preserve-common reset groups 0/1/2/3/5 (preserving 4/6) or full 363-record reset.", .status=Status::very_high, .va=0x14023A130ULL, .evidence_passes={30,31,32}},
        {.id="dmc3.scene.CSceneGame.Update", .parent_id="dmc3.scene.CSceneGame", .kind=Kind::method, .name="CSceneGame::Update", .summary="Produces gameplay transition results and writes gameplay re-entry flags on specific branches.", .status=Status::very_high, .va=0x14023A200ULL, .evidence_passes={30,31}},
        {.id="dmc3.scene.CSceneStartMenu", .parent_id="dmc3.scene-lifecycle", .kind=Kind::class_type, .name="CSceneStartMenu", .summary="Start-menu scene with a confirmed full LoadedResource reset at teardown.", .status=Status::very_high, .evidence_passes={30}},
        {.id="dmc3.scene.CSceneStartMenu.Teardown", .parent_id="dmc3.scene.CSceneStartMenu", .kind=Kind::method, .name="CSceneStartMenu::Teardown", .summary="Performs full reset of all 363 LoadedResource records at broad scene boundary.", .status=Status::very_high, .va=0x140242C90ULL, .evidence_passes={30}},
        {.id="dmc3.scene.CSceneGameMain", .parent_id="dmc3.scene-lifecycle", .kind=Kind::class_type, .name="CSceneGameMain", .summary="Primary gameplay inner scene that requests, claims, consumes and releases stage composite components.", .status=Status::very_high, .evidence_passes={30,31,32}},
        {.id="dmc3.scene.CSceneGameMain.Init", .parent_id="dmc3.scene.CSceneGameMain", .kind=Kind::method, .name="CSceneGameMain::Init", .summary="Reads current gameplay/stage ID and starts primary composite request.", .status=Status::very_high, .va=0x14023E610ULL, .evidence_passes={30,32}},
        {.id="dmc3.scene.CSceneGameMain.Teardown", .parent_id="dmc3.scene.CSceneGameMain", .kind=Kind::method, .name="CSceneGameMain::Teardown", .summary="Drops claims for stage kinds0/1/2 then invokes loader cleanup/zero-claim sweep.", .status=Status::very_high, .va=0x14023B2C0ULL, .evidence_passes={30,32}},
        {.id="dmc3.scene.CSceneMgrRoot.Map", .parent_id="dmc3.scene-lifecycle", .kind=Kind::function, .name="CSceneMgrRoot transition map", .summary="Top-level scene transition matrix for scene IDs 0 Boot,1 Opening,2 StartMenu,3 MisSelect,4 Game,5 GameMain,6 Demo,7 MisStart,8 Result,9 Ending.", .status=Status::very_high, .va=0x140240540ULL, .evidence_passes={31}},
        {.id="dmc3.scene.CSceneMgrGame.Map", .parent_id="dmc3.scene-lifecycle", .kind=Kind::function, .name="CSceneMgrGame transition map", .summary="Inner gameplay scene transition matrix connecting GameMain, Demo, MisStart and Result outcomes.", .status=Status::very_high, .va=0x140240420ULL, .evidence_passes={31}},
        {.id="dmc3.scene.gameplay-reentry-flag", .parent_id="dmc3.scene-lifecycle", .kind=Kind::global, .name="g_gameplay_reentry_preserve_common", .summary="CA3610: gameplay-to-gameplay re-entry flag selecting common-resource preservation and altered incoming CSceneGame initialization.", .status=Status::very_high, .va=0x140CA3610ULL, .evidence_passes={30,31,32}},
        {.id="dmc3.scene.special-reentry-flag", .parent_id="dmc3.scene-lifecycle", .kind=Kind::global, .name="g_special_gameplay_reentry", .summary="CA3611: special whole-gameplay re-entry subcontroller mode used by one CUIDGoldOrb result path.", .status=Status::very_high, .va=0x140CA3611ULL, .evidence_passes={30,31}},
        {.id="dmc3.scene.CUIDGoldOrb", .parent_id="dmc3.scene-lifecycle", .kind=Kind::class_type, .name="CUIDGoldOrb", .summary="Death/continue UI object with Gold/Yellow orb continuation and scene-exit/restart results.", .status=Status::very_high, .evidence_passes={31}},
        {.id="dmc3.scene.CUIDGoldOrb.Ctor", .parent_id="dmc3.scene.CUIDGoldOrb", .kind=Kind::method, .name="CUIDGoldOrb::CUIDGoldOrb", .summary="Recovered constructor for death/continue UI object.", .status=Status::very_high, .va=0x1402918E0ULL, .evidence_passes={31}},
        {.id="dmc3.scene.CUIDGoldOrb.Factory", .parent_id="dmc3.scene.CUIDGoldOrb", .kind=Kind::function, .name="CUIDGoldOrb::Create", .summary="Factory allocating 0x19C0-byte object.", .status=Status::very_high, .va=0x140291AD0ULL, .evidence_passes={31}},
        {.id="dmc3.scene.CUIDGoldOrb.GetResult", .parent_id="dmc3.scene.CUIDGoldOrb", .kind=Kind::method, .name="CUIDGoldOrb::GetResult", .summary="Returns completion result only when object state reaches 6.", .status=Status::very_high, .va=0x140291D50ULL, .evidence_passes={31}},
        {.id="dmc3.scene.CUIDGoldOrb.StateMachine", .parent_id="dmc3.scene.CUIDGoldOrb", .kind=Kind::state_machine, .name="CUIDGoldOrb state machine", .summary="Result1 Gold consume/in-place; result2 Yellow consume/inner GameMain restart; result3 Mission Select; result4 whole CSceneGame re-entry.", .status=Status::high, .va=0x140292020ULL, .evidence_passes={31}},

        {.id="dmc3.stage.TypeInfoRootTable", .parent_id="dmc3.stage-resource-topology", .kind=Kind::table, .name="Stage TypeInfo root table", .summary="Stage logical ID is split by /100 and %100 to locate three-descriptor StageMain/StageCfg/StageEffect block.", .status=Status::very_high, .va=0x1405C4A50ULL, .evidence_passes={31,32}},
        {.id="dmc3.stage.st001", .parent_id="dmc3.stage-resource-topology", .kind=Kind::policy, .name="st001 composite receipt", .summary="Logical stage ID 1 resolves exact StageMain, StageCfg and StageEffect TypeInfos and follows CFG-first composite ordering.", .status=Status::very_high, .evidence_passes={32}},
        {.id="dmc3.stage.st001.main", .parent_id="dmc3.stage.st001", .kind=Kind::table, .name="st001 StageMain TypeInfo", .summary="loader kind0 / scr\\st001.pac / container-backed.", .status=Status::confirmed, .va=0x1405C4AE0ULL, .evidence_passes={32}},
        {.id="dmc3.stage.st001.cfg", .parent_id="dmc3.stage.st001", .kind=Kind::table, .name="st001 StageCfg TypeInfo", .summary="loader kind1 / room\\st001cfg.pac / container-backed; physical slot9 is consumed during composite preparation.", .status=Status::confirmed, .va=0x1405C4AF0ULL, .evidence_passes={32}},
        {.id="dmc3.stage.st001.effect", .parent_id="dmc3.stage.st001", .kind=Kind::table, .name="st001 StageEffect TypeInfo", .summary="loader kind2 / room\\st001_effect.pac / container-backed.", .status=Status::confirmed, .va=0x1405C4B00ULL, .evidence_passes={32}},
        {.id="dmc3.stage.common-static-effect", .parent_id="dmc3.stage-resource-topology", .kind=Kind::policy, .name="Persistent static-effect singleton", .summary="LoadedResource group4 singleton path eff\\static_effect.pac; preserved across selective gameplay re-entry.", .status=Status::very_high, .evidence_passes={30,31}},
        {.id="dmc3.stage.common-group6", .parent_id="dmc3.stage-resource-topology", .kind=Kind::policy, .name="Persistent common gameplay package group", .summary="LoadedResource group6 includes snd_stay, language-selected main message PAC and several id*.pac common packages; preserved across selective re-entry.", .status=Status::very_high, .evidence_passes={30,31,32}},

        {.id="dmc3.texture.CPtxManager", .parent_id="dmc3.texture-runtime", .kind=Kind::class_type, .name="CPtxManager", .summary="32-entry pointer-keyed PTX runtime bundle cache with explicit refcount/release.", .status=Status::high, .evidence_passes={24}},
        {.id="dmc3.texture.CPtxManager.global", .parent_id="dmc3.texture.CPtxManager", .kind=Kind::global, .name="g_ptx_manager", .summary="Global CPtxManager storage: 32 entries, stride 0x218.", .status=Status::high, .va=0x140D5B860ULL, .evidence_passes={24}},
        {.id="dmc3.texture.CPtxManager.LoadA", .parent_id="dmc3.texture.CPtxManager", .kind=Kind::method, .name="CPtxManager::LoadA", .summary="Caches by exact source pointer, parses source on miss, installs bundle with refcount1.", .status=Status::high, .va=0x140314E00ULL, .evidence_passes={24}},
        {.id="dmc3.texture.CPtxManager.LoadB", .parent_id="dmc3.texture.CPtxManager", .kind=Kind::method, .name="CPtxManager::LoadB", .summary="Second source parser/load path sharing pointer-key cache policy.", .status=Status::high, .va=0x140314FA0ULL, .evidence_passes={24}},
        {.id="dmc3.texture.CPtxManager.Release", .parent_id="dmc3.texture.CPtxManager", .kind=Kind::method, .name="CPtxManager::Release", .summary="Exact source-pointer lookup, decrement refcount, destroy retained runtime bundle when count reaches zero.", .status=Status::high, .va=0x140315180ULL, .evidence_passes={24}},
        {.id="dmc3.texture.RegisterRuntimeTextureRecordByKey", .parent_id="dmc3.texture-runtime", .kind=Kind::function, .name="RegisterRuntimeTextureRecordByKey", .summary="Registers runtime texture record in global pointer table indexed by recovered key; not a texture upload function.", .status=Status::high, .va=0x140033370ULL, .evidence_passes={24}},
        {.id="dmc3.texture.gfxTexture.Create", .parent_id="dmc3.texture-runtime", .kind=Kind::function, .name="gfxTexture::Create", .summary="Chooses one of three cache domains, deduplicates source descriptor, creates source-backed gfxTexture on miss.", .status=Status::high, .va=0x140046C40ULL, .evidence_passes={24}},
        {.id="dmc3.texture.gfxTexture.IsReady", .parent_id="dmc3.texture-runtime", .kind=Kind::function, .name="gfxTexture::IsReady", .summary="Ready immediately when runtime resource exists; otherwise source descriptor drives lazy creation.", .status=Status::high, .va=0x140046AF0ULL, .evidence_passes={24}},
        {.id="dmc3.texture.gfxTexture.Release", .parent_id="dmc3.texture-runtime", .kind=Kind::function, .name="gfxTexture::Release", .summary="Releases optional/primary runtime interfaces under ownership gate; exact COM interfaces remain unnamed.", .status=Status::high, .va=0x1400465E0ULL, .evidence_passes={24}},
    };
    return tree;
}

} // namespace

const std::vector<RecoveredSourceSymbol>& recovered_source_tree() noexcept {
    return tree_storage();
}

const RecoveredSourceSymbol* find_recovered_source_symbol(
    std::string_view id) noexcept {
    const auto& tree = tree_storage();
    const auto iterator = std::find_if(
        tree.begin(), tree.end(),
        [id](const RecoveredSourceSymbol& symbol) { return symbol.id == id; });
    return iterator == tree.end() ? nullptr : &*iterator;
}

std::vector<const RecoveredSourceSymbol*> recovered_source_children(
    std::string_view parent_id) {
    std::vector<const RecoveredSourceSymbol*> children;
    for (const auto& symbol : tree_storage()) {
        if (symbol.parent_id == parent_id) {
            children.push_back(&symbol);
        }
    }
    return children;
}

} // namespace dmc::rengine::profiles::dmc3
